---
name: Create release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release Tag:"
        type: string
      target_branch:
        description: "Target Branch:"
        type: string        
  workflow_call:
    inputs:
      release_tag:
        description: "Release Tag:"
        type: string
      target_branch:
        description: "Target Branch:"
        type: string  

env:
  RELEASE_TAG: ${{ inputs.release_tag }}
  TARGET_BRANCH: ${{ inputs.target_branch }}

permissions:
  contents: write

jobs:
  release:
    name: Create opendatahub-io/kubeflow release
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Invoke script to handle creating release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          ./.github/scripts/create-release.sh    

