name: Run Notebook Controller unit tests
on:
  push:
  pull_request:
    branches:
      - main
      - v1.9-branch
    paths:
      - .github/workflows/notebook_controller_unit_test.yaml
      - components/notebook-controller/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        check-latest: true
        go-version-file: components/notebook-controller/go.mod
        cache-dependency-path: components/notebook-controller/go.sum

    - name: Run unit tests
      run: |
        cd components/notebook-controller
        make test

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./components/notebook-controller/cover.out
        disable_search: true
